version: '2'

services:
  game-server:
    build: .
    volumes:
      - ./resources:/GameServer/resources
      - ./configurations:/GameServer/configurations
    ports:
      - 80:80
    environment:
      - DB_URL=/GameServer/configurations/database
      - RESOURCES_PATH=/GameServer/resources
